export const FontAwesomeIcons = {
    HOME: 'fas fa-home',
    USER: 'fas fa-user-alt',
    USER_CIRCLE: 'fas fa-user-circle',
    USERS: 'fas fa-users',
    MESURE: 'fas fa-ruler-horizontal',
    INFO: 'fas fa-eye',
    MODIFIER: 'fas fa-edit',
    SUPPRIMER: 'fas fa-trash-alt',
    TACHOMETRE: 'fas fa-tachometer-alt',
    STORE: 'fas fa-store-alt',
    FOLDER_OPEN: 'far fa-folder-open',
    FOLDER: 'far fa-folder',
    PLATEAU: 'fas fa-dolly-flatbed',
    SHOPPING_CART: 'fas fa-shopping-cart',
    MONEY: 'fas fa-money-bill',
    CALENDAR: 'fas fa-calendar-check',
    PARAMETRES: 'fas fa-sliders-h',
    EMAIL: 'far fa-envelope',
    PHONE: 'fas fa-phone',
    GENRE: 'fas fa-venus-mars',
    LONG_LEFT_ARROW: 'fas fa-long-arrow-alt-left',
    HEART: 'fas fa-heart',
    GLOBE: 'fas fa-globe'
}